char_replacements = {
    "space": " ",
    "enter": "[enter]",
    "ctrl": "[ctrl]",
    "alt": "[alt]",
    "shift": "[shift]",
    "caps lock": "[capslock]",
    "num lock": "[numlock]",
    "shiftright": "[rshift]",
    "altright": "[ralt]",
    "delete": "[delete]",
    "pause": "[pause]",
    "print screen": "[printscreen]",
    "backspace": "[backspace]",
    "esc": "[esc]",
    "windows": "[win]",
    "up": "[uparrow]",
    "down": "[downarrow]",
    "left": "[leftarrow]",
    "right": "[rightarrow]",
    "page up": "[pgup]",
    "page down": "[pgdn]",
    "f1": "[f1]",
    "f2": "[f2]",
    "f3": "[f3]",
    "f4": "[f4]",
    "f5": "[f5]",
    "f6": "[f6]",
    "f7": "[f7]",
    "f8": "[f8]",
    "f9": "[f9]",
    "f10": "[f10]",
    "f11": "[f11]",
    "f12": "[f12]"
}